baseURL = "https://ooprod.ru/"
DefaultContentLanguage = "ru"
languageCode = "ru"
title = "ООП и в продакшн" 
copyright="Подкаст \"ООП и в продакшн\""
googleAnalytics = "UA-71522545-6"


themedir = "themes"
theme="podcast-theme"

[params]
  # itunes settings
  author = "ooprod.ru"
  description = "Расслабленные беседы об информационных технологиях с легким образовательным послевкусием"
  type = "episodic" # or serial (see https://help.apple.com/itc/podcasts_connect/#/itcb54353390)
  ownerName = "Ivan Belyavtsev"
  ownerEmail = "djbelyak@gmail.com"
  category = "Technology" # (see https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12)
  subcategory = "Software How-To" # Erase if you haven't it
  artwork = "/images/artwork.png"
  explicit = "no"
  itunesLink = "https://geo.itunes.apple.com/ru/podcast/%D0%BE%D0%BE%D0%BF-%D0%B8-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%BA%D1%88%D0%BD/id1465231106?mt=2&app=itunes"

  # debug features
  #debugCSS = true # show a layout without details
  #withoutMinification = true

  # yandex metrika
  yandexMetrika = "53928256"


[menu]

  [[menu.main]]
    name = "Домой"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Выпуски подкаста"
    url = "/podcast/"
    weight = 2

  #[[menu.main]]
  #  name = "Подписки"
  #  url = "/subscription/"
  #  weight = 3

[blackfriday] 
  hrefTargetBlank = true
